#!/bin/sh

#SBATCH --job-name=ds001747-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds001747-mriqc/.reproman/jobs/local/20220823-221849-62d6/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds001747-mriqc/.reproman/jobs/local/20220823-221849-62d6/stderr

#SBATCH --nodes=19
#SBATCH --ntasks=92
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds001747-mriqc/.reproman/jobs/local/20220823-221849-62d6

module load launcher
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 91); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

"$LAUNCHER_DIR"/paramrun